platform :ios, '13.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'Common7Sdk_Example' do
  
  inhibit_all_warnings!
  use_frameworks!
  
  pod 'Common7Sdk', :path => '../'

  target 'Common7Sdk_Tests' do
    inherit! :search_paths

  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
    end
end
